"""fix relationships and constraints

Revision ID: 54f91b5363f2
Revises: c79c118397b2
Create Date: 2026-02-16 16:30:58.544491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f91b5363f2'
down_revision: Union[str, Sequence[str], None] = 'c79c118397b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_category_user_name'), 'categories', type_='unique')
    op.create_unique_constraint('uq_category_user_name', 'categories', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_user_name', 'categories', type_='unique')
    op.create_unique_constraint(op.f('uq_category_user_name'), 'categories', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
